# This is a basic workflow to help you get started with Actions

name: python_application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install pylint
          pip install coverage
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          black --check .
          coverage run -m --source=. unittest discover
          coverage xml          
      # Upload to Code Coverage
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
